//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.cn", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 资金调整 的本地化字符串。
        /// </summary>
        internal static string Financing_RecordAdjust_Title {
            get {
                return ResourceManager.GetString("Financing_RecordAdjust_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 归档 的本地化字符串。
        /// </summary>
        internal static string Financing_RecordDetail_Filing {
            get {
                return ResourceManager.GetString("Financing_RecordDetail_Filing", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所有未处理借贷 的本地化字符串。
        /// </summary>
        internal static string Financing_RecordDetail_NoDealLoan {
            get {
                return ResourceManager.GetString("Financing_RecordDetail_NoDealLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string Financing_RecordDetail_SelectAll {
            get {
                return ResourceManager.GetString("Financing_RecordDetail_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 资金详细 的本地化字符串。
        /// </summary>
        internal static string Financing_RecordDetail_Title {
            get {
                return ResourceManager.GetString("Financing_RecordDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 总额 的本地化字符串。
        /// </summary>
        internal static string Financing_RecordDetail_Total {
            get {
                return ResourceManager.GetString("Financing_RecordDetail_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 录入时间 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_AddDate {
            get {
                return ResourceManager.GetString("Financing_Record_AddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 金额 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_Amount {
            get {
                return ResourceManager.GetString("Financing_Record_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 借贷类型 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_LoanType {
            get {
                return ResourceManager.GetString("Financing_Record_LoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记账类型 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_RecordType {
            get {
                return ResourceManager.GetString("Financing_Record_RecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_Remark {
            get {
                return ResourceManager.GetString("Financing_Record_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 账号类型 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_Summary {
            get {
                return ResourceManager.GetString("Financing_Record_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记一笔 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_Title {
            get {
                return ResourceManager.GetString("Financing_Record_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 到 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_To {
            get {
                return ResourceManager.GetString("Financing_Record_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理账户类型 的本地化字符串。
        /// </summary>
        internal static string Financing_Record_ToSummary {
            get {
                return ResourceManager.GetString("Financing_Record_ToSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加账号类型 的本地化字符串。
        /// </summary>
        internal static string Financing_SummaryType_AddType {
            get {
                return ResourceManager.GetString("Financing_SummaryType_AddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 账号类型 的本地化字符串。
        /// </summary>
        internal static string Financing_SummaryType_Title {
            get {
                return ResourceManager.GetString("Financing_SummaryType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 欢迎使用 的本地化字符串。
        /// </summary>
        internal static string System_Index_Title {
            get {
                return ResourceManager.GetString("System_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限不足 的本地化字符串。
        /// </summary>
        internal static string System_RoleError_Title {
            get {
                return ResourceManager.GetString("System_RoleError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限不足 的本地化字符串。
        /// </summary>
        internal static string System_RoleError_Txt {
            get {
                return ResourceManager.GetString("System_RoleError_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登录名 的本地化字符串。
        /// </summary>
        internal static string User_LogOn_DescribeName {
            get {
                return ResourceManager.GetString("User_LogOn_DescribeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string User_LogOn_DescribePassword {
            get {
                return ResourceManager.GetString("User_LogOn_DescribePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登陆 的本地化字符串。
        /// </summary>
        internal static string User_LogOn_DescribeSubmit {
            get {
                return ResourceManager.GetString("User_LogOn_DescribeSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登陆 的本地化字符串。
        /// </summary>
        internal static string User_LogOn_Title {
            get {
                return ResourceManager.GetString("User_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string _Comm_Back {
            get {
                return ResourceManager.GetString("_Comm_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string _Comm_Delete {
            get {
                return ResourceManager.GetString("_Comm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string _Comm_Save {
            get {
                return ResourceManager.GetString("_Comm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string _Comm_Search {
            get {
                return ResourceManager.GetString("_Comm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误参数 的本地化字符串。
        /// </summary>
        internal static string _Error_Comm_Para {
            get {
                return ResourceManager.GetString("_Error_Comm_Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误查询日期 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_RecordDetail_Date {
            get {
                return ResourceManager.GetString("_Error_Financing_RecordDetail_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误查询记账类型 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_RecordDetail_RecordType {
            get {
                return ResourceManager.GetString("_Error_Financing_RecordDetail_RecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误查询账号类型 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_RecordDetail_Summary {
            get {
                return ResourceManager.GetString("_Error_Financing_RecordDetail_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误记账金额(需大于0) 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_Record_Amount {
            get {
                return ResourceManager.GetString("_Error_Financing_Record_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误借贷类型 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_Record_LoanType {
            get {
                return ResourceManager.GetString("_Error_Financing_Record_LoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误记账类型 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_Record_RecordType {
            get {
                return ResourceManager.GetString("_Error_Financing_Record_RecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注长度过长,不能超过50个字符 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_Record_Remark {
            get {
                return ResourceManager.GetString("_Error_Financing_Record_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误账号类型 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_Record_Summary {
            get {
                return ResourceManager.GetString("_Error_Financing_Record_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误转账账号类型 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_Record_ToSummary {
            get {
                return ResourceManager.GetString("_Error_Financing_Record_ToSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加的账号类型输入错误(不能为空且最大10字节) 的本地化字符串。
        /// </summary>
        internal static string _Error_Financing_SummaryType_Add {
            get {
                return ResourceManager.GetString("_Error_Financing_SummaryType_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 账号或密码错误 的本地化字符串。
        /// </summary>
        internal static string _Error_User_LogOn_LoginFail {
            get {
                return ResourceManager.GetString("_Error_User_LogOn_LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 {
        ///    &quot;add_summary_null&quot;: &quot;请填写添加的账号类型&quot;,
        ///    &quot;sure_summary_delete&quot;: &quot;确定要删除此条账号类型?&quot;,
        ///    &quot;add_record_null_amount&quot;: &quot;记账金额不能为空&quot;,
        ///    &quot;add_record_error_amount&quot;: &quot;错误记账金额(需大于0)&quot;,
        ///    &quot;add_record_null_date&quot;: &quot;添加时间不能为空&quot;,
        ///    &quot;add_record_error_date&quot;: &quot;无效日期时间&quot;,
        ///    &quot;adjust_record_null_data&quot;: &quot;记账金额不能为空&quot;,
        ///    &quot;adjust_record_error_data&quot;: &quot;错误记账金额(需大于0)&quot;,
        ///    &quot;sure_record_delete&quot;: &quot;确定删除?&quot;,
        ///    &quot;sure_record_filing&quot;: &quot;确定归档?&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string _JS_Financing {
            get {
                return ResourceManager.GetString("_JS_Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 {
        ///    &quot;need_input&quot;: &quot;填写账号密码&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string _JS_User {
            get {
                return ResourceManager.GetString("_JS_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 待开发 的本地化字符串。
        /// </summary>
        internal static string _Layout_menu_DevMessageBoard {
            get {
                return ResourceManager.GetString("_Layout_menu_DevMessageBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 理财 的本地化字符串。
        /// </summary>
        internal static string _Layout_menu_Financing {
            get {
                return ResourceManager.GetString("_Layout_menu_Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string _Layout_menu_LogOut {
            get {
                return ResourceManager.GetString("_Layout_menu_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记一笔 的本地化字符串。
        /// </summary>
        internal static string _Layout_menu_Record {
            get {
                return ResourceManager.GetString("_Layout_menu_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 资金调整 的本地化字符串。
        /// </summary>
        internal static string _Layout_menu_RecordAdjust {
            get {
                return ResourceManager.GetString("_Layout_menu_RecordAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 明细 的本地化字符串。
        /// </summary>
        internal static string _Layout_menu_RecordDetail {
            get {
                return ResourceManager.GetString("_Layout_menu_RecordDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 账户类型 的本地化字符串。
        /// </summary>
        internal static string _Layout_menu_Summary {
            get {
                return ResourceManager.GetString("_Layout_menu_Summary", resourceCulture);
            }
        }
    }
}
