//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWallet.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qdm211529417_dbEntities : DbContext
    {
        public qdm211529417_dbEntities()
            : base("name=qdm211529417_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_loan_type> t_loan_type { get; set; }
        public virtual DbSet<t_manager> t_manager { get; set; }
        public virtual DbSet<t_record_type> t_record_type { get; set; }
        public virtual DbSet<t_role> t_role { get; set; }
        public virtual DbSet<t_setting> t_setting { get; set; }
        public virtual DbSet<t_summary> t_summary { get; set; }
        public virtual DbSet<t_summary_record> t_summary_record { get; set; }
    }
}
