//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWallet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_summary_record
    {
        public int summ_reco_id { get; set; }
        public int mana_id { get; set; }
        public int reco_type_code { get; set; }
        public int summ_id { get; set; }
        public int summ_tran_id { get; set; }
        public int loan_type_code { get; set; }
        public decimal amount { get; set; }
        public decimal tran_amount { get; set; }
        public string remark { get; set; }
        public System.DateTime add_time { get; set; }
        public bool is_deal { get; set; }
    }
}
